### ISSUE TITLE
Graphs are incorrect under RedHat Linux 7.4

### ISSUE THREAD

**Issue by maciek01170** [psi-probe/psi-probe#1100]
Hello, 
I am having an issue when displaying graphs in psi-probe after the update from Redhat 7.3 to 7.4, I suspect the OS update broke libraries used by jfreechart, unfortunately no idea how to fix this, I cannot move back to 7.3.
Any idea?

Thank you very much. 
Cheers  ... Maciek

The screenshot : 
<img width="948" alt="capture d ecran 2017-08-16 a 13 39 20" src="https://user-images.githubusercontent.com/16017699/29361598-a3c58af4-8288-11e7-901c-9e36b2433556.png">

**Comment by dogilvie** [comment]
Possibly related is this issue on StackOverflow: https://stackoverflow.com/questions/45569367/upgrade-rhel-from-7-3-to-7-4-arrayindexoutofboundsexception-in-sun-font-composi

I was experiencing an issue in psi-probe, for me the graphs would not display at all due to the exception:

java.lang.ArrayIndexOutOfBoundsException: 0
    at sun.font.CompositeStrike.getStrikeForSlot(CompositeStrike.java:75)

The following resolved my issue, but I am not sure this is the best solution. Or if this will help your problem.

sudo yum install dejavu-serif-fonts

**Comment by hazendaz** [comment]
think this was long since fixed.  if not please open new ticket.
