### ISSUE TITLE
cannot filter log level

### ISSUE THREAD

**Issue by 8debug** [psi-probe/psi-probe#1196]
It is very good! I like it.  I seem some problems when I use it.

My project use springboot 1.5、SLF4J 1.7、Log4j

![image](https://user-images.githubusercontent.com/3394927/43813323-c67bdb06-9af7-11e8-8641-d88341e0fd77.png)

log can not show information with filter level
I am sorry about my english

**Comment by hazendaz** [comment]
Normally that will show whatever is there and after you change it to say "ERROR", the prior will still display but new should start dropping down to the respective type.  I'm a bit surprised though that you are using log4j with springboot when by default springboot is slf4j/logback.  I don't use log4j myself as it is obsolete now for 6 years.  So if this is not behaving as you would expect and I described, then I would need help from you getting a pull request that might otherwise address the issue.  I tend to use logback for all my projects and do know that it works in this area without issue.

**Comment by hazendaz** [comment]
I should also note, this is done via the classpath, so if for some reason it's unable to properly flip that on the classpath, you might have stack trace errors logged but not shown and it would simply do nothing in that case.  You might want to look through your logs to see if it notes anything when flipping the flag.

**Comment by hazendaz** [comment]
closing as misunderstanding of use.  It snot filtering.  It is changing the logging level.  Filtering would require something entirely new which I don't have time for.  Agree it would be nice but would need someone to contribute a solution.  Closing for now.
