### ISSUE TITLE
Your project psi-probe/psi-probe is using buggy third-party libraries [WARNING]

### ISSUE THREAD

**Issue by FDU-SE-LAB** [psi-probe/psi-probe#1229]
Hi, there!
We are a research team working on third-party library analysis. We have found that some widely-used third-party libraries in your project have major/critical bugs, which will degrade the quality of your project. We highly recommend you to update those libraries to new versions.    
We have attached the buggy third-party libraries and corresponding jira issue links below for you to have more detailed information.
  1  commons-io commons-io (pom.xml)
  version: 2.6

  Jira issues:
  .gitattributes not correctly applied
  affectsVersions:2.6
  https://issues.apache.org/jira/projects/IO/issues/IO-516?filter=allopenissues
  FilenameUtils.normalize should verify hostname syntax in UNC path
  affectsVersions:2.6
  https://issues.apache.org/jira/projects/IO/issues/IO-559?filter=allopenissues
  Missing Javadoc in FilenameUtils causing Travis-CI build to fail
  affectsVersions:2.6
  https://issues.apache.org/jira/projects/IO/issues/IO-570?filter=allopenissues

  2  ch.qos.logback logback-classic (pom.xml)
  version: 1.2.3

  Jira issues:
  missing log files and log entries when using SizeAndTimeBasedRollingPolicy 
  affectsVersions:1.2.3
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-1361?filter=allopenissues

Sincerely~
FDU Software Engineering Lab
Jan 7th,2019

**Comment by hazendaz** [comment]
@FDU-SE-LAB Thank you for this information!  I was already planning to upgrade logback along with slf4j due to CVE being flagged on slf4j (even the fixed version).  I'm testing that now and will be applying that one shortly.  As a result of slf4j issue, logback is a required upgrade so catching that as well.  I'll take a look at these other issues shortly.  Again thanks!

**Comment by hazendaz** [comment]
I don't mean to discount your suggestions here but the .gitattributes has nothing to do with usage of that library.  It was an issue with how they were using gitattributes within the physical build.  It was fixed in 2.6, we are on 2.6, so there is no issue.  The FileName issue, while I agree that affects this project, apache has not yet released the fixes so nothing I care to do right now.  The last item on javadoc is again specific to their project and has nothing to do with usage.

That said, I've addressed the item that can be addressed here.  I'm otherwise closing this as complete.  If you do find other issues more applicable to this library please let me know and/or raise pull requests.  The versions on final cuts will auto pick up as dependabot runs on this and I'm pretty up-to-date with exception of some libraries where I need help as noted in 'issues'.
