### ISSUE TITLE
Tomcat 8- PSI-PROBE without Authentication option?

### ISSUE THREAD

**Issue by iam333** [psi-probe/psi-probe#1240]
Thanks in advance!

I would like to know if there is posible to configure PSI Probe in Tomcat 8 to acces without user/password (anonymous)?

thanks!

**Comment by hazendaz** [comment]
No.  At best just configure same user id/ password such as probe/probe.

If you really need this option you would need to raise a PR and base that type of access most likely lower access level than the current lowest.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by iam333** [comment]
Thanks for your answer!
But, I have a doubt ... In tomcat 6, if I delete the tomcat-users.xml, it works fine! It would be possible that changing something in tomcat 8, will it work?

**Comment by hazendaz** [comment]
Tomcat 6 is very old, the underlying psi probe for that version was 2.4.x which was full of issues.  If the same does not work now it could have been fixed by numerous things since fixed either in tomcat specs, psi probe, or spring/spring security.  Regardless, if that same scenario doesn't work in tomcat 7, 8.5, or 9 (nevermind 8 as its no longer supported), then I would say security was increased which is a good thing.  Security itself is necessary around this specific application as it provides significant amount of data of a running container.  Lack of any security would certainly be less than that of any current read access as it simply has to be secured.  For example, the least security currently still provides large amount of data of the running JVM and I don't think under any circumstances you would want that exposed without account/password protection.  Only very basic information should be available in that sort of situation and probably only as much as stating the context that are running and very limited data.

**Comment by iam333** [comment]
Thank you so much for everything.
I absolutely agree with your comment on the need to secure a platform, but there are cases in which it is not necessary, even, this securization is a problem. As for example, it occurs in software development environments.
For this reason, I think it is more than understandable, that you could allow the possibility of activating or deactivating this security to an administrator, since he is ultimately responsible for it. And this without taking into consideration, that this allows a greater versatility of the product.

thank you so much!!!

**Comment by hazendaz** [comment]
Closing issue as we will not weaken security unnecessarily.  Plus user usage was with obsolete version of this library with suggestions on bugs it most certainly had or even tomcat had.  This does not apply to latest.
