### ISSUE TITLE
Issue for chinese Language

### ISSUE THREAD

**Issue by Jiadi-Cheng** [psi-probe/psi-probe#1274]
How can I show Chinese character in Logs?

![image](https://user-images.githubusercontent.com/45381244/54621101-2a849480-4aa2-11e9-9deb-d8be599d147a.png)

**Comment by hazendaz** [comment]
@Jiadi-Cheng Is the physical log content ok with chinese characters and its just the display?  If just the display, its likely just using the wrong encoding there.  Maybe if you have time you can try to figure out the exact point of issue and raise a pull request?  I'm not sure otherwise when I can get to this.

**Comment by hazendaz** [comment]
closing as I don't know how to resolve this.  Encoding is the issue but I'm not a Chinese speaker and have no clue how to proceed.  Help would be needed here to make this work.  A lot of this repo hinges on utf-8.
