### ISSUE TITLE
About Log Tab

### ISSUE THREAD

**Issue by zz90z** [psi-probe/psi-probe#1310]
I have run tomcat9 as windows service，and then I open the probe's Log tab，i found my app log，but I can't find tomcat_stdout.log or tomcat_stderr.log in list，how to solve this problem?
if i run tomcat9/bin/startup.bat，i can find all logs in list

**Comment by hazendaz** [comment]
@zz90z See numerous issues with logs.  The problem is that the application currently needs to read only from the classpath.  If it is unable to do so, you won't see any of the logs.  This is a well known problem with psi probe and needs volenteers to fix the issues.  The reason for classpath only is so you can change logging at runtime but I think as many others would agree we just want to see the logs.  I don't have time myself to address the issue overall and the logic is a bit complicated.  I would need help getting all logs to properly display in read only mode.

**Comment by hazendaz** [comment]
For any missing logs, go to the stdout.properties in WAR and change it to include additional items you need.  On this case, the naming is off from standards which is fine, add that way and they will show up.
