### ISSUE TITLE
how to show log  of rolled ?

### ISSUE THREAD

**Issue by 765362546** [psi-probe/psi-probe#1329]
log4j.appender.xx=org.apache.log4j.RollingFileAppender
log4j.appender.xxx=org.apache.log4j.DailyRollingFileAppender

only show the current log in logs tab,can show the log of rolled?

**Comment by hazendaz** [comment]
The logs are based on what is available on the classpath.  Achived generally would not be on the classpath and as such not accessible.  Logs in general has been a huge gap on this product.  Because it wants to look at classpath so you can then change logging levels on the fly, it has resulted in very unfriendly usage as it pertains to logging in general.  If you look through 'issues' you will find logs is probably the largest issue.  To gain some better way of showing all logs, new support will need added.  I'm open for pull requests bringing in more wide support but otherwise don't have time to dedicate to showing logs.

**Comment by 765362546** [comment]
think you very much!
