### ISSUE TITLE
psi probe error with ssl tomcat 9.0.24

### ISSUE THREAD

**Issue by drmaciel** [psi-probe/psi-probe#1439]
I did the deploy of probe v. 3.3.0 on tomcat v. 9.0.24 with ssl

I set up web.xml on tomcat:

   	<security-constraint>
		<display-name>No anonymous access</display-name>
		<web-resource-collection>
			<web-resource-name>All areas</web-resource-name>
			<url-pattern>/*</url-pattern>
		</web-resource-collection>
		<user-data-constraint>
			<transport-guarantee>CONFIDENTIAL</transport-guarantee>
		</user-data-constraint>
	</security-constraint>

I set up web.xml on probe:

   	<security-constraint>
		<display-name>No anonymous access</display-name>
		<web-resource-collection>
			<web-resource-name>All areas</web-resource-name>
			<url-pattern>/*</url-pattern>
		</web-resource-collection>
		<user-data-constraint>
			<transport-guarantee>CONFIDENTIAL</transport-guarantee>
		</user-data-constraint>
	</security-constraint>

When accessing the probe, i get the message: "You do not have sufficient privileges to access this page. Please use the navigation bar to choose another area or click "back" button in your browser.".

What configuration needs to be done to resolve the error?

**Comment by hazendaz** [comment]
You have to setup the tomcat users in order to use psi probe.  It work fine in all.  The error you have is either lack of setting up tomcat users or failure to use the correct account and password.  There is nothing that needs done to anything in psi probe itself.  The war as is.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by drmaciel** [comment]
Added users to the file tomcat-users.xml as per the setting below:

    <role rolename="admin"/>
    <role rolename="admin-gui"/>
    <role rolename="admin-script"/>
    <role rolename="manager"/>
    <role rolename="manager-gui"/>
    <role rolename="manager-script"/>
    <role rolename="manager-jmx"/>
    <role rolename="manager-status"/>
    <role rolename="probeuser" />
    <role rolename="poweruser" />
    <role rolename="poweruserplus" />
    <user name="admin" password="" roles="admin,manager,admin-gui,admin-script,manager-gui,manager-script,manager-jmx,manager-status,probeuser,poweruser,poweruserplus" />


But I still get the message: "You do not have sufficient privileges to access this page."

**Comment by hazendaz** [comment]
@drmaciel You have mixed tomcat and psi probe configuration.  Try separating them.  I don't recall off hand but I think you need 'probe' as the user for probe.  However, that might just be a suggestion since that is how I've always used it.

**Comment by drmaciel** [comment]
Hi @hazendaz, thank you for your help. I added the user probe to the file tomcat-users.xml:

    <role rolename="admin"/>
    <role rolename="admin-gui"/>
    <role rolename="admin-script"/>
    <role rolename="manager"/>
    <role rolename="manager-gui"/>
    <role rolename="manager-script"/>
    <role rolename="manager-jmx"/>
    <role rolename="manager-status"/>
    <role rolename="probeuser" />
    <role rolename="poweruser" />
    <role rolename="poweruserplus" />
    <user name="admin" password="senha" roles="admin,manager,admin-gui,admin-script,manager-gui,manager-script,manager-jmx,manager-status" />
    <user name="probe" password="senha" roles="manager-gui,manager,poweruser,poweruserplus,probeuser" />


Restarted the tomcat and get the same message.

**Comment by hazendaz** [comment]
I don't think this is a psi probe concern.  Based on looking at this again, you went into tomcat and caused it to be entirely secured at that level.  I would suggest reading tomcat documents again as a lot of items are not supposed to be set in their web.xml.  The behaviour of it not working makes perfect sense because tomcat knows nothing about psi probe and you entirely locked out the application best I can tell.  While some tools like NVS complain if web.xml in tomcat is not misconfigured, it's a lack of that tooling understanding webapps in general.  I don't know if that is your case but I suspect it is since you configured tomcat to lock out apps.
