### ISSUE TITLE
Unable to properly monitor Javaweb projects

### ISSUE THREAD

**Issue by lifei636** [psi-probe/psi-probe#1461]
My project path is <Context path="" docBase=" "medicaltriagesystem" debug="0" reloadable="true" />
After probe login status prompt down, enter the project and click start prompt
Please check the Tomcat logs. We will greatly appreciate it if you share the information with us. Sharing this information through our issue tracker or ourDiscussion board will help us find and correct this problem as soon as possible!
Turn on the probe. Log prompt
10:15:00. 002 ERROR} {Probe_Quartz - 5 [psiprobe. Beans. ContainerListenerBean] Failed to query - thread pool psiprobe. Model. The JMX. Dcefc ThreadPoolObjectName @ 609
10:15:00. 002 ERROR} {Probe_Quartz - 5 [psiprobe. Beans. ContainerListenerBean] Failed to query - thread pool psiprobe. Model. The JMX. Efae ThreadPoolObjectName @ 5339
But my project can be accessed normally

**Comment by hazendaz** [comment]
@lifei636 Looks like you have 2 quotes before the docbase.  I cannot otherwise determine what you are doing here.  The error is security in that it won't tell you in the console why it failed.  The logs are not telling me anything here other than it cannot reach thread pool.  But considering you have 2 quotes before medicaltraiagesystem, I suspect its your configuration.

**Comment by hazendaz** [comment]
closing issue as never heard back and issue appears improper quoting on docBase as noted.
