### ISSUE TITLE
cannot display the connector

### ISSUE THREAD

**Issue by auqf** [psi-probe/psi-probe#1486]
![image](https://user-images.githubusercontent.com/8895540/71136122-b77d9980-223e-11ea-9f50-855383f0bb8d.png)

**Comment by hazendaz** [comment]
@auqf Can you provide more information on what exactly your issue is in regards too?  Its nice to see that a 500 error occurs but I have no clue how to fix it without more details on your specific configuration and usage.  If you can tell me what you did to arive at this point, that would be helpful.

**Comment by hazendaz** [comment]
closing as old and many changes since, if still an issue, open new ticket with more details.
