### ISSUE TITLE
Access to psi-probe.slack.com

### ISSUE THREAD

**Issue by eduardKiyko** [psi-probe/psi-probe#1497]
Hello all, does anybody know, who I can contact to get invitation to psi-probe.slack?

**Comment by hazendaz** [comment]
Currently it's only used internally for alerting git commits.  Only the maintainers are listed for usage and its otherwise mostly quiet otherwise.  Last contributor comment on slack was me back in 2017.  If there is a big want by others to be in the general channel, I can look at adding others but at the moment it would not benefit you very much.

**Comment by hazendaz** [comment]
Leaving this open to see if there is other interest :)

**Comment by eduardKiyko** [comment]
okay, thank you! I just had several questions regarding psi-probe logging and logs format, I am going to create Splunk add-on for psi-probe, but I don't know what fields to extract and what do they mean. Maybe you know where I can find this kind of information?

**Comment by hazendaz** [comment]
There isn't much documentation.  But any questions should be asked to the user group as you may find better luck there going through this.  I sort of inherited this and its rather easy to use so I have not spent cycles trying to add documentation beyond what you can find here and on the wiki.
