### ISSUE TITLE
Provide instructions for setting up the project in Eclipse

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#16]
```
We should provide instructions on the wiki for how to set up the project in
Eclipse.
```

Original issue reported on code.google.com by `MALfunct...@gmail.com` on 22 Apr 2009 at 3:55

**Comment by hazendaz** [comment]
Closing this issue.  Both plugins mentioned in this are long obsolete and completely unnecessary doing more harm than good.  The project is full on maven done the right way so all one does is import it and builds.  It doesn't even require an IDE to work with in its current setup.  Not sure it's worth stating anything in docs about how to do a basic import to an IDE.  That might have made sense years ago but I think these days most people working with this do know how to use maven and it's all the same when done right.  Given no one has reported issues with trying to get going I don't see much need otherwise.
