### ISSUE TITLE
pl/project13/maven/git/GitCommitIdMojo has been compiled by a more recent version of the Java Runtime

### ISSUE THREAD

**Issue by BigData-YC** [psi-probe/psi-probe#2460]
[ERROR] Failed to execute goal io.github.git-commit-id:git-commit-id-maven-plugin:5.0.0:revision (git-commit-id) on project psi-probe: Execution git-commit-id of goal io.github.git-commit-id:g
it-commit-id-maven-plugin:5.0.0:revision failed: Unable to load the mojo 'revision' in the plugin 'io.github.git-commit-id:git-commit-id-maven-plugin:5.0.0' due to an API incompatibility: org.
codehaus.plexus.component.repository.exception.ComponentLookupException: pl/project13/maven/git/GitCommitIdMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by hazendaz** [comment]
That is a build error. As it states use correct jdk to build project.  It's defined both in pom.xml and gh actions ci file.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: YC ***@***.***>
Sent: Monday, March 27, 2023 5:16:48 AM
To: psi-probe/psi-probe ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [psi-probe/psi-probe] pl/project13/maven/git/GitCommitIdMojo has been compiled by a more recent version of the Java Runtime (Issue #2460)


[ERROR] Failed to execute goal io.github.git-commit-id:git-commit-id-maven-plugin:5.0.0:revision (git-commit-id) on project psi-probe: Execution git-commit-id of goal io.github.git-commit-id:g
it-commit-id-maven-plugin:5.0.0:revision failed: Unable to load the mojo 'revision' in the plugin 'io.github.git-commit-id:git-commit-id-maven-plugin:5.0.0' due to an API incompatibility: org.
codehaus.plexus.component.repository.exception.ComponentLookupException: pl/project13/maven/git/GitCommitIdMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by BigData-YC** [comment]
I'm using idea, and all the JDK I've set up are 8...
After the project downloads, the `mvn package` is executed directly
![image](https://user-images.githubusercontent.com/47716603/229008758-5b5ce63b-cba9-43f6-a2bb-309f2e2abf97.png)

**Comment by hazendaz** [comment]
Requires jdk 11 to build it.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
FYI.  Next release of this project isn't even going to support jdk8 runtime.  Unless contributing you don't need to build anyways.  Every piece of the is in maven central.  The next major release is going to spring 6 and jakarta so it will be jdk 17 only and tomcat 10.1 or 11 only.  While I plan to keep a support line it is unlikely to change very often at that point.

The enforcer should be telling you build needs jdk 11.  Many plugins require 11.  It's currently cross compiled to 8 but as noted times are changing.  I'd highly suggest regardless of what your intentions to use jdk 17.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
The part you marked are the profiles in the build.  Most are not necessary to build and those that are auto activate.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BigData-YC** [comment]
3Q

**Comment by hazendaz** [comment]
closing as non issue and not sure what last comment even meant.  Please use proper jdk to build if you need to or use distributed releases that are already precompiled as notes indicated.
