### ISSUE TITLE
OS-specific packages such as .rpm or .deb for easy installation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#254]
```
Please describe the feature you would like to see added.

OS-specific packages developed and maintained properly for psi-probe. An 
example would be existing debian package supporting tomcat6 such as 
tomcat6-webapps or tomcat6-user which depends on tomcat6 with added 
functionalities. 

How will this feature make Probe better?

It may help more people get started using probe by simply doing "sudo apt-get 
install tomcat-probe" or similar.
```

Original issue reported on code.google.com by `chenw...@chenwang.org` on 8 Nov 2011 at 4:28

**Comment by moimael** [comment]
Why the wontfix label ? I provided some rpm (the same we use in production, maybe not the latest release though) to fix this issue.

**Comment by MALfunction84** [comment]
Because it had already been closed as stale before you added that. I wasn't looking at content, just labels. My apologies. Reopening.

Unfortunately, I have no idea what to do with the files you provided.

**Comment by moimael** [comment]
Fair enough :) We could integrate them to the build process. Maybe use some maven-rpm-plugin to be able to package to war and also rpm (and deb why not ?)

**Comment by jander99** [comment]
I'm wondering on the use case of this.  There is no "standard" place for
Tomcat to be installed to, and typically if you're building a linux stack
you aren't using the version of Tomcat in the repository because it's
probably several versions behind.  Same with Java.  If we build an rpm
package, it will be deployed to one place on the server, and the
instructions would then be "find your $CATALINA_HOME/conf/ directory and
copy this probe.xml file into it in order to actually deploy this on
Tomcat."   I don't think there is any work being saved by that.

Can you shed some light on why this feature would be good to have?

**Comment by hazendaz** [comment]
closing as old.  the distributions are in maven central.  If needed bad enough, use 'curl' or build a process around it.  Given I'm last man standing here and barely at that, I have little desire to build other tool delivery solutions just to tick a box that it was done.  Given low activity here and now 8 years later, it wasn't all that important to start with.
