### ISSUE TITLE
Crash probe after deploy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#307]
```
What steps will reproduce the problem?
1. deploy war
2. access

-> Acces probe page error.

* Tomcat6 (6.0.35-1+squeeze2)
* probe 2.3.1
* Debian 6.0.5 x86_64
* Java:
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02, mixed mode)
```

Original issue reported on code.google.com by `stephane...@gmail.com` on 6 Aug 2012 at 7:23

Attachments:
- [error.log](https://storage.googleapis.com/google-code-attachments/psi-probe/issue-307/comment-0/error.log)

**Comment by hazendaz** [comment]
This is very old and could have been caused by a couple of problems.  If import directives contained ';' at end that would cause issue on newer tomcats as it's wrong.  Jdk could have been installed incorrectly.  If reported again with more information I'll take another look but after googling, this seems consistent with general issues more than with psi probe.
