### ISSUE TITLE
Could not write stats data

### ISSUE THREAD

**Issue by ralf-devop** [psi-probe/psi-probe#3134]
After updating to version 4.x, i get an error message "Could not write stats data" in probe logfile, every 5 minutes.
For further information, see attached logfile.

My enviroment:
Red Hat Enterprise Linux 8.8
Tomcat 9.0.62-18.redhat_00016.1.el8jws
java-17-openjdk 17.0.9.0.9-2.el8

It seems alright with java-11-openjdk.

[probe.log](https://github.com/psi-probe/psi-probe/files/14384569/probe.log)

**Comment by hazendaz** [comment]
Hi @ralf-devop, this one is something you need to do in tomcat.  Tomcat comes with jdk java options already set with the following in catalina.sh

# Add the JAVA 9 specific start-up parameters required by Tomcat
JDK_JAVA_OPTIONS="$JDK_JAVA_OPTIONS --add-opens=java.base/java.lang=ALL-UNNAMED"
JDK_JAVA_OPTIONS="$JDK_JAVA_OPTIONS --add-opens=java.base/java.io=ALL-UNNAMED"
JDK_JAVA_OPTIONS="$JDK_JAVA_OPTIONS --add-opens=java.base/java.util=ALL-UNNAMED"
JDK_JAVA_OPTIONS="$JDK_JAVA_OPTIONS --add-opens=java.base/java.util.concurrent=ALL-UNNAMED"
JDK_JAVA_OPTIONS="$JDK_JAVA_OPTIONS --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED"
export JDK_JAVA_OPTIONS

I presume you have an older file that does not contain that information.  You may want to make sure your tomcat configuration is up to date.  Can you check that?

**Comment by hazendaz** [comment]
This one specifically is what is required for xstream to work.

```
JDK_JAVA_OPTIONS="$JDK_JAVA_OPTIONS --add-opens=java.base/java.util=ALL-UNNAMED"
```

**Comment by ralf-devop** [comment]
Great! It works properly now. Thanks for this piece of advice.

**Comment by ralf-devop** [comment]
Done!

**Comment by hazendaz** [comment]
@ralf-devop If you want, feel free to raise a PR to the readme to note that issue in case others run into that issue.  I can see folks updating tomcat but not necessarily always pulling the configuration since historically its just worked without changes.  I'm pretty sure one other person asked about this a few years back.  For what its worth, at the moment I'm still using tomcat 9.0.52 when doing testing with this in general.  I hope to have myself upgraded though to latest in coming months as I cleanup some of the baggage of 100% manual updates.  I plan to further share those up into the psi-probe space to give users a quick example on how I do it.  Today I keep those in my personal space but it was bulky as I applied binaries directly.  I'm rewriting it all to be a quick maven build so switching versions will be simple with things such as ssh configured (even if weak key) just for testing reasons. 

At any rate, would be nice to see a contribution on how you ended up applying the solution for what was missing and solved the issue :)
