### ISSUE TITLE
No able to access log.out in the 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#392]
```
What steps will reproduce the problem?
1.Go to the application Log's screen
2.Click on log.out
3.

What is the expected result?
See the log.out file

What happens instead?
Exception(Stack trace attached)
Importantly 
1. com.googlecode.psiprobe.controllers.logs.SetupFollowController - log4j log 
"root" not found
2.com.googlecode.psiprobe.tools.logging.log4j.Log4JLoggerAccessor - Could not 
wrap appender: null java.lang.IllegalArgumentException: appender is null

What version of Probe are you using?
2.3.3

What environment (browser version, Tomcat version, JVM version, server OS)?
Browser : Problem in all latest browser
Tomcat version : 7
OS : linux

Please provide any additional information below.
(Attach logs or stack traces as files instead of pasting the contents
here.)

```

Original issue reported on code.google.com by `rahulbha...@gmail.com` on 30 Dec 2013 at 3:13

Attachments:
- [Exception.txt](https://storage.googleapis.com/google-code-attachments/psi-probe/issue-392/comment-0/Exception.txt)

**Comment by yujiaao** [comment]
the access log not show up in logs list

when I add tomcat valve to server.xml

```
        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log." suffix=".txt"
               pattern="%h %l %u %t &quot;%r&quot; %s %b" />
```

that will produce log files such as:

    `localhost_access_log.2017-09-19.txt`

but I cannot see it in the PSI Probe log list

**Comment by hazendaz** [comment]
@yujiaao access logs are still not supported.  There are quite a few logs not supported.  Please review the issues and if you know how to fix the issues, pull requests are welcome.  Because of how this project tries to read logs, they all come off classpath of various logger types.  This would need bridged to work.  The alternative is to go into the java configuration for spring on loggers and simply add hard definitions of logs you want to show up to force them.

**Comment by hazendaz** [comment]
logs being tracked separately.  This log shows but what doesn't show is the timestamped ones, that will be addressed separately.
