### ISSUE TITLE
Enable Coveralls code coverage tool + Cobertura

### ISSUE THREAD

**Issue by jander99** [psi-probe/psi-probe#461]
I have a pull request that I based on my own fork with the #460 pull request outstanding, however I have done the integrations for Coveralls and it seems to be working fine.  You can see the results on my own branch here: https://coveralls.io/r/jander99/psi-probe.  I will wait to issue the pull request until #460 has been approved or denied, if there is interest in adding code coverage.  

Here are the docs on the tool:  https://github.com/trautonen/coveralls-maven-plugin

You can see in my dashboard there are two builds, the difference being 'via'.  The travis CI integration does not require any private keys, but running the mvn cobertura:cobertura coveralls:report command does require the -DrepoToken flag to be set, just like in the documentation.  

Thoughts?

**Comment by MALfunction84** [comment]
My personal feeling on tools like this is that they generate a lot of busywork. The code is fairly tightly coupled unfortunately, especially the parts that interact with a running server.  This means there are a number of untestable components.  This is already known.  I'd hate for someone to see the low code coverage and, with all the best intentions, submit PRs that test code in dire need of refactoring. (More on this in #456.)

I'm not ruling anything out, but I don't think this is the right time. Leaving the issue open if someone can make a good case to pull the trigger now.

Related: I had to reject #460 because Travis-CI is no longer accepting requests to add MacOS workers. Let's keep an eye out and see if they get more.

**Comment by jander99** [comment]
Partly agree on the busy work.  I believe there are some annotations that can cause cobertura to ignore methods that aren't testable in most cases.  I can do some research on that later as it would educate me on other projects.

**Comment by MALfunction84** [comment]
I mentioned refactoring in a prior comment, but there was no issue at the time. Filed as #473.

**Comment by MALfunction84** [comment]
While code coverage reports won't fix tight coupling, it will definitely shine a spotlight on it. This project is in dire need of refactoring so that it is more testable. That's one of many goals for 3.0.

Decoupling server integration (#473) will demand integration testing. I'm open to suggestions on how best to automate this.

Fixed by 9b60975.
