### ISSUE TITLE
Increase minimum Java version to 1.6

### ISSUE THREAD

**Issue by MALfunction84** [psi-probe/psi-probe#472]
Java 1.4 and 1.5 are at end-of-life. We no longer need to support them. Missing language features in 1.4 especially are holding the project back from using newer libraries (#449).

**Comment by robertoschwald** [comment]
Especially the 1.4 setting is hitting devs using Intellij IDEA. Since Intellij currently does not support testSource/testTarget maven-compiler settings (IDEA-85478), one is unable to compile in this IDE without setting source / target to 1.5, as core/test uses annotations.

**Comment by diogosantana** [comment]
@robertoschwald To enhance the discussion, check #492 history.

I do believe this will be "automatically" fixed after 2.4 when Java 1.4 and 1.5 will be dropped.

**Comment by hazendaz** [comment]
tomcat 7 requires minimum java 6.  Since this is now the minimum tomcat 7 version, this can be immedaitely.

http://tomcat.apache.org/whichversion.html

**Comment by hazendaz** [comment]
I've got a local build where I did a prelimanary full upgrade including all the jars to java 6 level.  I'll have to do a little more testing and of course would bring in slowly.  Famous last words...so far so good.

**Comment by jander99** [comment]
According to http://www.oracle.com/technetwork/java/eol-135779.html Java 6 is EOL but has extended support until 2018.  Since enterprise customers will probably be the last, Java 6 sounds reasonable.  However if we come to a situation where we have to choose a bunch of development time for 6 vs 7, let's reevaluate. I don't want us to get stuck on the IE8 development around, i.e. writing code simple to handle one corner case.

**Comment by MALfunction84** [comment]
This change slated for milestone 3.0.0, which is basically "immediately." If a good PR comes in, I'll merge it.

As long as we're supporting Tomcat 7, we should probably continue to support Java 6.
