### ISSUE TITLE
Support for TomEE ManagedDataSource

### ISSUE THREAD

**Issue by xRodney** [psi-probe/psi-probe#519]
In the current version of Psi Probe, no data sources are found on TomEE 1.7.0 if they are configured in tomee.xml (http://tomee.apache.org/datasource-config.html)

Data sources on TomEE are of class [org.apache.openejb.resource.jdbc.managed.local.ManagedDataSource](http://people.apache.org/~dblevins/staging-052/legal/content/org/apache/openejb/openejb-core/4.5.0/openejb-core-4.5.0-javadoc.jar.contents/org/apache/openejb/resource/jdbc/managed/local/ManagedDataSource.html) which has getDelegate method. From the delegate, all necessary info can be retrieved.

Is TomEE oficially supported or planned to be? Should I submit a PR?

**Comment by jander99** [comment]
If you have a fix in place that works, submit a PR and we'll see what
happens.  Otherwise, we are currently planning 3.0 in the forums (link in
readme.md) so maybe we can make this issue a feature enhancement for that
version.

Looks like ManagedDataSouce implements javax.sql.DataSource.  So it's not
that we don't support TomEE, its that we just happen to not support
ManagedDataSource as a DataSource yet.
