### ISSUE TITLE
Upload Maven-generated site to gh-pages

### ISSUE THREAD

**Issue by MALfunction84** [psi-probe/psi-probe#536]
Piggybacking off of effort from #497, I'd like for the gh-pages to be a build of the Maven-generated site, reports and all. There is definitely a [plugin](https://github.com/github/maven-plugins#site-plugin) for this, but it needs to be set up carefully in Travis. Only commits to master should rebuild the site, not PRs or commits to other branches.

**Comment by hazendaz** [comment]
I've found that plugin to be buggy and stopped using it after 0.12 which is currently latest.  I started instead using this instead which leverages maven in a cleaner way without any additional plugins.

https://github.com/trajano/wagon-git

**Comment by hazendaz** [comment]
This is a simple effort to get working.  I'll take this on when I get some time to address.  The site will generate either on demand or during the physical release process.  I haven't otherwise got it working on other projects during master hit as it uses ssh and https is all I know to setup things in travis currently but will eventually look into that.

**Comment by hazendaz** [comment]
Completed maven site deployment via gh-pages.  Original text on the github generated site ported over to readme on site.  Site is the project site otherwise.  I'm going to open a new ticket for enhancing and cleaning that up now that it is working.  This will occur when requested by us or on phsyical maven releases.  It won't otherwise release.
