### ISSUE TITLE
Javadoc for public APIs

### ISSUE THREAD

**Issue by MALfunction84** [psi-probe/psi-probe#540]
While #512 addressed code formatting issues, there are still a number of checkstyle warnings related to missing Javadoc on public APIs. I'd like to get these all cleaned up and then strongly enforce checkstyle going forward.

**Comment by hazendaz** [comment]
There is an eclipse plugin called 'jautodoc'.  While not a perfect solution, it does a nice job of adding javadocs which gets past the checkstyles issues.  While it won't build out lots of wisdom in the javadocs, it's a pretty good starting point.  I'm not sure if this would be something you would want to do though since it hides the overall concern and possibly means the issues will never be addressed.  However, it's really good about finding bad javadocs as well and fixing them so java 8 javadoc link works.

http://jautodoc.sourceforge.net/

**Comment by jander99** [comment]
We could have a task to review all javadoc that exists with a separate PR
for that.  I think what we need is a skeleton to be filled in later.  All
the boilerplate setup to document is a method is tedious so if there is a
plugin that can fill some stuff in and we can come back around later to
flesh it all out, then let's do that.

**Comment by MALfunction84** [comment]
I'm torn.

On the one hand, auto-generated documentation is sweeping the problem under the rug. We need to actually put effort into writing the documentation, and the checkstyle warnings are a constant reminder of that.

On the other hand, *all* the documentation needs to be reviewed, including the ones that currently pass checkstyle. On top of that, I'd really like to have failing checkstyle to fail the build so Travis-CI can fail any PRs that don't conform to style. Saves me some effort.

I think I agree with you both.

**Comment by hazendaz** [comment]
Javadocs are in place using jautodoc.  Leaving this open until we are satisfied on all javadoc needs.

**Comment by hazendaz** [comment]
Due to lack of time to care much about javadocs, I'm pretty good with the auto generated ones.  If anyone asks for more, I'll kindly suggest a PR to update them.  Otherwise think this is good to close.

**Comment by MALfunction84** [comment]
IMO, it still needs to be done, but it shouldn't block releases. More of a housekeeping item.

**Comment by hazendaz** [comment]
closing as known issue.  If anyone wants to expand on javadocs so be it but don't need the ticket open.
