### ISSUE TITLE
Maven Versioneye

### ISSUE THREAD

**Issue by jander99** [psi-probe/psi-probe#681]
@hazendaz http://blog.versioneye.com/2016/02/10/versioneye-maven-plugin-3-7-0/

Is it possible to set up Versioneye to the organization, and then update the travis script so that we have continuous version checking?

**Comment by hazendaz** [comment]
Nice!  I'll look into this plugin.  Versioneye has been emailing me otherwise.  We are up-to-date with exception to some legacy components used in the build for displaytag.  However, I just forked the source earlier this week and play to take that to release soon which will get us all the way current on our existing usage.

Our readme links out there but not sure if that is still under me and/or visable for others to review.  I'll look into this.  Thanks for finding it.

**Comment by hazendaz** [comment]
I have added the plugin which using the default `mvn versioneye:list` is somewhat interesting.  Other than that since we are hooked up, it's hooked up under my account/organization.  While I can create another it still seems like it's simply under my organization.  Plus using this plugin seems like it might need to expose API information on a key and potentially could be a bad situation if that accidently got released.  So for now, leaving project as-is as versioneye does what we need and versions are up-to-date.  Otherwise closing this out for now.
