### ISSUE TITLE
In the newest version of 3.0.0, the issue of "Parallel Deployment on Tomcat 7 still fails #545 " is still not solved.

### ISSUE THREAD

**Issue by mengdq** [psi-probe/psi-probe#721]
Do you have any plan to solve the issue of Parallel Deployment on Tomcat 7 still fails #545 ?

**Comment by hazendaz** [comment]
Any possibily you might be able to contibute a PR for this issue?


Sent from Outlook Mobile






On Thu, Apr 21, 2016 at 7:12 PM -0700, "mengdq" <notifications@github.com> wrote:





 Do you have any plan to solve the issue of Parallel Deployment on Tomcat 7 still fails #545 ?

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/psi-probe/psi-probe/issues/721

**Comment by hazendaz** [comment]
Closing issue as this is a duplicate.
