### ISSUE TITLE
Connectors 无图表数据

### ISSUE THREAD

**Issue by 501956430** [psi-probe/psi-probe#772]
环境：
tomcat 7
jdk8
windows 7

自2.3.3版本之后，其他版本Connectors都无图表数据，尝试过的版本有: 2.4 、3.0.0 Milestone 2、3.0.0 Milestone 3，在此之前一直使用的是2.3.3版本
以上版本都是下载的独立的war包

![image](https://cloud.githubusercontent.com/assets/20204491/17274847/519ef668-5726-11e6-9071-bed5c621f7f0.png)

![image](https://cloud.githubusercontent.com/assets/20204491/17274848/51dcf828-5726-11e6-9c4b-dfcf912b4f2a.png)

**Comment by hazendaz** [comment]
This issue has since been resolved.  Please try master and let me know if that works for you.

Get Outlook for Android<https://aka.ms/ghei36>



On Sun, Jul 31, 2016 at 1:57 AM -0400, "501956430" <notifications@github.com<mailto:notifications@github.com>> wrote:


环境：
tomcat 7
jdk8
windows 7

自2.3.3版本之后，其他版本Connectors都无图表数据，尝试过的版本有: 2.4 、3.0.0 Milestone 2、3.0.0 Milestone 3，在此之前一直使用的是2.3.3版本
以上版本都是下载的独立的war包

[image]<https://cloud.githubusercontent.com/assets/20204491/17274847/519ef668-5726-11e6-9071-bed5c621f7f0.png>

[image]<https://cloud.githubusercontent.com/assets/20204491/17274848/51dcf828-5726-11e6-9c4b-dfcf912b4f2a.png>

―

**Comment by 501956430** [comment]
谢谢！
