### ISSUE TITLE
Not working for TomEE 7.0.1

### ISSUE THREAD

**Issue by tonywestonuk** [psi-probe/psi-probe#805]
I get:
java.lang.IllegalStateException: No container found for your server: Apache Tomcat (TomEE)/8.5.3 (7.0.1)

If I add the -Dtomee.keep-server-info=true  option, I still get.

java.lang.IllegalStateException: No container found for your server: Apache Tomcat/8.5.3

**Comment by hazendaz** [comment]
tomEE isn't supported as of the moment but I can add that.  As for the other, can you confirm if you are running off current master or if you were trying one of the milestones for 3.0.0?  If the milestone, that is known issue.  If off master, I'll take a look as I thought I fixed that.

**Comment by tonywestonuk** [comment]
I

Sent from my iPhone
Tried it with both the 2.4 version, and latest 3 snapshot.... nothing works

I was using tomee 7.0.1, rather than tomee 1.7 which I have success with before

**Comment by hazendaz** [comment]
Thanks.  If you use the lastest master and build on your own, the option '-Dtomee.keep-server-info=true' should work now.  Version 8.5.x while I had put it into the milestones I forgot to have it get included in the WAR.  There is also a way via our instructions (forget at the moment) to force it to use what you expect it to pickup.  I'll work on getting tomEE into later revisions.  Personally glad to see they finally moved off very old tomcat versions and making it more of their own solution.  I am in the middle of some very heavy lifting to get spring completely annotation based so your best option currently is to just build from master then use that option you found.  Or if you have time, go into our 8.5 module and patch it to support tomcat 8.5 then send a pull request.  I'll merge it pretty quickly.  I otherwise just got back from vacation so not sure how soon I will be back into a working state at moving this forwards.

Thanks,

Jeremy

**Comment by hazendaz** [comment]
I'm closing this for now.  This is in the code base.  Has been for a while.  Please build off the master as this does work off the master.

**Comment by hazendaz** [comment]
@tonywestonuk Do you know if tomEE entirely skipped tomcat 8.0.x?

**Comment by tonywestonuk** [comment]
I really do not know, sorry.

I'll think I'll wait until you push out a release, rather than build myself....   Im still in the build stage of the app I am working on, and dont really need the monitoring urgently that psiprobe can provide.

thanks  very much for getting the bug fixed now - It'll be in a full release when I need it!
