### ISSUE TITLE
PSI - Probe not working on tomcat 6.0.33

### ISSUE THREAD

**Issue by jarvis100** [psi-probe/psi-probe#806]
[probe.txt](https://github.com/psi-probe/psi-probe/files/507802/probe.txt)

I tried the following 

Probe uses ServerInfo to determine what server it's running on. If you've changed this property on your server or if you are using an unsupported server, Probe may give an error when you try to access it. However, you can bypass this issue by forcing Probe to use a specific server adapter:

    1.Open probe.war and edit /WEB-INF/spring-probe-resources.xml.
    2.Find the "containerWrapper" bean.
    3.Toggle the "forceFirstAdaptor" value from false to true.
    4.Ensure that the adapter for your version of Tomcat is listed first in the list of "adaptorClasses." For example, if you are deploying Probe to Tomcat 6, ensure that com.googlecode.psiprobe.Tomcat60ContainerAdaptor is listed first.

**Comment by hazendaz** [comment]
Version 2.4 is what you want for tomcat 6.  We otherwise no longer support tomcat 6.

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Oct 4, 2016 at 2:39 AM -0400, "jarvis100" <notifications@github.com<mailto:notifications@github.com>> wrote:


probe.txt<https://github.com/psi-probe/psi-probe/files/507802/probe.txt>

-

**Comment by hazendaz** [comment]
Closing issue as we do not support tomcat 6 in version 3.0.0.  Either use 2.4.0 version or upgrade to more recent tomcat version.  For reference, tomcat 6 is being officially EOL in December.  We haven't released psi probe 3.0.0 yet and it will be after tomcat 6 is officially deprecated and retired by apache.
