### ISSUE TITLE
Blank screen after Deployment...

### ISSUE THREAD

**Issue by tachtler** [psi-probe/psi-probe#832]
Hi,

**OS:** CentOS-7
**Tomcat:** 7.0.54 (with security backports from RedHat/CentOS)

after` Deployment | Upload application (basic)` was finished, a blank seccen was shown, insted of the success message and the link to see the compiled jsp's (for example).

Thank you,
Klaus.

**Comment by hazendaz** [comment]
This is a current open issue.  It doesnt affect the upload itself.  For an immediate fix build master with spring 4.2.x.  otherwise just hang tight until spring is fully converted to annotations in psi probe.  Unfortunately best i can do currently.

What its doing is getting 405 errors under the hood.  It works fine with annotations but im only about 80% complete switching over.

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Dec 2, 2016 at 7:46 AM -0500, "Klaus Tachtler" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

OS: CentOS-7
Tomcat: 7.0.54 (with security backports from RedHat/CentOS)

afterDeployment | Upload application (basic) was finished, a blank seccen was shown, insted of the success message and the link to see the compiled jsp's (for example).

Thank you,
Klaus.

-

**Comment by tachtler** [comment]
Hi Jeremy,

o.k. good to know, I understand the problem. But don't hurry with the annotation migration. 

In the next CentOS release (Version 7.3) - coming soon - tomcat will be rebased to version 7.0.69.
We will see, what happen with psi-probe and the new version of tomcat under CetnOS-7.

Best whishes
Klaus.

**Comment by hazendaz** [comment]
@tachtler If you need anything with CentOS that we are missing, please let me know.  I'm otherwise closing this as there is an earlier open issue against same problem (clearing the clutter!).

**Comment by tachtler** [comment]
Hi Jeremy,

closing the issue is o.k. for me.

Thank you
Klaus.

**Comment by hazendaz** [comment]
@tachtler This has been corrected on master.  Please try rebuilding and give it a try.  Let me know if it works out for you.
