### ISSUE TITLE
SSL redirect gives error

### ISSUE THREAD

**Issue by paradoxicalNL** [psi-probe/psi-probe#848]
Probe works fine here, but as soon as I set force TLS in Tomcat I get the following error:

_You do not have sufficient privileges to access this page. Please use the navigation bar to choose another area or click "back" button in your browser._

Tomcat 7.0.73 (ssl is installed and other apps load without problem):

My users file:

```
<role rolename="probeuser" />
<role rolename="poweruser" />
<role rolename="poweruserplus" />
<role rolename="manager" />
<role rolename="manager-gui" />

 <user username="admin" password="myadminpass" roles="manager-gui" />
```

  <user username="admin" password="admin" roles="manager-gui" />

Tomcat web.xml
   
```
<security-constraint>
		<web-resource-collection>
		<web-resource-name>Protected Context</web-resource-name>
			<url-pattern>/*</url-pattern>
		</web-resource-collection>
		<user-data-constraint>
			<transport-guarantee>CONFIDENTIAL</transport-guarantee>
		</user-data-constraint>
</security-constraint>
```

When I access probe over ssl without this security-constraint enabled it works fine!

**Comment by PeanutChen** [comment]
I have the same problem

**Comment by hazendaz** [comment]
Where exactly is this being configured?  This setting is supposed to be in web.xml of a webapp not at the tomcat level.  The web.xml files in servlet 3.x get applied together.  If that is being set at tomcat level, it's going to conflict the web applications settings.  In fact, I would suspect it will simply ignore the webapp one all together.  That is an important factor because that is where the roles are setup.  So yes you would get a page like that.  I don't see anywhere on tomcat site that it suggests to touch their web.xml to do such a thing.  I'll test to confirm but if you could point me to where tomcat suggested such a configuration in case that is a suggested practice that I missed.  I've never actually seen that setup before and don't understand why it would be done that way since you can disable http to start with in tomcat.

**Comment by paradoxicalNL** [comment]
I configured this in the tomcat web.xml. When I create constraints per application in this file, probe works. Using a wildcard however breaks probe.

The reason for using /* is that I use many different apps, using a wildcard is efficient, and I only have to add 1 security contraint.

I do not fully understand why this happens.

**Comment by hazendaz** [comment]
I have tested this and it works fine in tomcat 8.5.14.  It seems tomcat 8.5.14 does merge content even within xml block together and thus works.  It's possible earlier versions do not handle this.

@paradoxicalNL What version of tomcat are you using?  Version of psi probe? Please share your web.xml configuration so I can replicate issue.

**Comment by hazendaz** [comment]
@paradoxicalNL Sorry I see you were original reporter.  I'm checking tomcat 7 now...

8.5.x though works without question.  If tomcat 7.0.x doesn't, I suspect a problem with the implementation of the specs at that time and that isn't likely something I can even fix but I will check it out.

**Comment by hazendaz** [comment]
Confirmed - Tomcat 7.0.x does not support this behaviour.  You can fix by adding the roles into tomcat web.xml.
